export const ActionType = {
  SET_USER: 'SET_USER',
  GET_USER: 'GET_USER',
  REMOVE_USER: 'REMOVE_USER',
  SET_COURSES: 'SET_COURSES',
  SET_COURSE: 'SET_COURSE',
  REMOVE_COURSE: 'REMOVE_COURSE',
  UPDATE_ADD_SUCCESS: 'UPDATE_ADD_SUCCESS',
  ADD_LOADING: 'ADD_LOADING',
  UPDATE_EDIT_SUCCESS: 'UPDATE_EDIT_SUCCESS',
  EDIT_LOADING: 'EDIT_LOADING',
  UPDATE_DELETE_SUCCESS: 'UPDATE_DELETE_SUCCESS',
  DELETE_LOADING: 'DELETE_LOADING',
};
